spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:
    source-db:
      url: jdbc:ucanaccess://D:\\date.mdb;ignoreCase=true;showSchema=true;memory=false
      username: Admin
      driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    target-db:
      url: jdbc:postgresql://localhost:5432/sbsdb
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
    migration-db:
      url: jdbc:postgresql://localhost:5432/sbsdb-migration
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

  liquibase:
    url: jdbc:postgresql://localhost:5432/sbsdb-migration
    user: postgres
    password: root
    change-log: liquibase/changelog/liquibase-changelog-master.xml

migration:
  job:
    cron: 0 0 1 * * *

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8210/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh, scheduledtasks
  endpoint:
    health:
      show-details: always