spring:
  datasource:
    source-db:
      url: jdbc:ucanaccess:///tmp/date.mdb;ignoreCase=true;showSchema=true;memory=false
    target-db:
      url: jdbc:postgresql://postgres:5432/sbsdb
    migration-db:
      url: jdbc:postgresql://postgres:5432/sbsdb-migration

  liquibase:
    url: jdbc:postgresql://postgres:5432/sbsdb-migration

  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8210/eureka
