application:
  discovery-server:
    alias: ds
    port: 8210
  subscriber-manager:
    alias: sm
    name: subscriber-manager
    uri: lb://${application.subscriber-manager.name}
  data-actuator:
    alias: da
    name: data-actuator
    uri: lb://${application.data-actuator.name}
  report-generator:
    alias: rg
    name: report-generator
    uri: lb://${application.report-generator.name}
  notificator-email:
    alias: ne
    name: notificator-email
    uri: lb://${application.notificator-email.name}
  notificator-sms:
    alias: ns
    name: notificator-sms
    uri: lb://${application.notificator-sms.name}

spring:
  cloud:
    gateway:
      routes:
        # business requests
        - id: subscriber-manager-requests
          uri: ${application.subscriber-manager.uri}
          predicates:
            - Path=/sub/v1/**

        # system requests
        ## actuator of discovery server
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.discovery-server.port}
          predicates:
            - Path=/${application.discovery-server.alias}/actuator
          filters:
            - RewritePath=/${application.discovery-server.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.discovery-server.port}
          predicates:
            - Path=/${application.discovery-server.alias}/actuator/**
          filters:
            - RewritePath=/${application.discovery-server.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of subscriber manager
        - id: subscriber-manager-actuator-base-path
          uri: ${application.subscriber-manager.uri}
          predicates:
            - Path=/${application.subscriber-manager.alias}/actuator
          filters:
            - RewritePath=/${application.subscriber-manager.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: ${application.subscriber-manager.uri}
          predicates:
            - Path=/${application.subscriber-manager.alias}/actuator/**
          filters:
            - RewritePath=/${application.subscriber-manager.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of data actuator
        - id: data-actuator-actuator-base-path
          uri: ${application.data-actuator.uri}
          predicates:
            - Path=/${application.data-actuator.alias}/actuator
          filters:
            - RewritePath=/${application.data-actuator.alias}/actuator, /actuator
        - id: data-actuator-actuator-sub-paths
          uri: ${application.data-actuator.uri}
          predicates:
            - Path=/${application.data-actuator.alias}/actuator/**
          filters:
            - RewritePath=/${application.data-actuator.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of report generator
        - id: report-generator-actuator-base-path
          uri: ${application.report-generator.uri}
          predicates:
            - Path=/${application.report-generator.alias}/actuator
          filters:
            - RewritePath=/${application.report-generator.alias}/actuator, /actuator
        - id: report-generator-actuator-sub-paths
          uri: ${application.report-generator.uri}
          predicates:
            - Path=/${application.report-generator.alias}/actuator/**
          filters:
            - RewritePath=/${application.report-generator.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of notificator email
        - id: subscriber-manager-actuator-base-path
          uri: ${application.notificator-email.uri}
          predicates:
            - Path=/${application.notificator-email.alias}/actuator
          filters:
            - RewritePath=/${application.notificator-email.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: ${application.notificator-email.uri}
          predicates:
            - Path=/${application.notificator-email.alias}/actuator/**
          filters:
            - RewritePath=/${application.notificator-email.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of notificator sms
        - id: subscriber-manager-actuator-base-path
          uri: ${application.notificator-sms.uri}
          predicates:
            - Path=/${application.notificator-sms.alias}/actuator
          filters:
            - RewritePath=/${application.notificator-sms.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: ${application.notificator-sms.uri}
          predicates:
            - Path=/${application.notificator-sms.alias}/actuator/**
          filters:
            - RewritePath=/${application.notificator-sms.alias}/actuator/(?<path>.*), /actuator/$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${application.discovery-server.port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0