application:
  subscriber-manager:
    port: 8230
  data-actuator:
    port: 8240

spring:
  cloud:
    gateway:
      routes:
        # business requests
        - id: subscriber-manager-requests
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/sub/v1/**
        # system requests
        ## actuator of subscriber manager
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/sm/actuator
          filters:
            - RewritePath=/sm/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/sm/actuator/**
          filters:
            - RewritePath=/sm/actuator/(?<path>.*), /actuator/$\{path}
        ## actuator of data actuator
        - id: data-actuator-actuator-base-path
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/sm/actuator
          filters:
            - RewritePath=/sm/actuator, /actuator
        - id: data-actuator-actuator-sub-paths
          uri: http://localhost:${application.data-actuator.port}
          predicates:
            - Path=/da/actuator/**
          filters:
            - RewritePath=/da/actuator/(?<path>.*), /actuator/$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8210/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh
  endpoint:
    health:
      show-details: always