spring:
  cloud:
    gateway:
      routes:
        - id: subscriber-manager-requests
          uri: http://localhost:8230
          predicates:
            - Path=/sub/v1/**
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:8230
          predicates:
            - Path=/sm/actuator/**
          filters:
            - RewritePath=/sm/actuator/(?<path>.*), /actuator/$\{path}
        - id: subscriber-manager-actuator-sub-path
          uri: http://localhost:8230
          predicates:
            - Path=/sm/actuator
          filters:
            - RewritePath=/sm/actuator, /actuator
        - id: data-actuator-actuator
          uri: http://localhost:8240
          predicates:
            - Path=/da/actuator/**
          filters:
            - RewritePath=/da/actuator/(?<path>.*), /actuator/$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8210/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh
  endpoint:
    health:
      show-details: always