application:
  discovery-server:
    alias: ds
    port: 8210
  subscriber-manager:
    alias: sm
    port: 8230
  data-actuator:
    alias: da
    port: 8240
  notificator-email:
    alias: ne
    port: 8260
  notificator-sms:
    alias: ns
    port: 8270

spring:
  cloud:
    gateway:
      routes:
        # business requests
        - id: subscriber-manager-requests
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/sub/v1/**

        # system requests
        ## actuator of discovery server
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.discovery-server.port}
          predicates:
            - Path=/${application.discovery-server.alias}/actuator
          filters:
            - RewritePath=/${application.discovery-server.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.discovery-server.port}
          predicates:
            - Path=/${application.discovery-server.alias}/actuator/**
          filters:
            - RewritePath=/${application.discovery-server.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of subscriber manager
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/${application.subscriber-manager.alias}/actuator
          filters:
            - RewritePath=/${application.subscriber-manager.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.subscriber-manager.port}
          predicates:
            - Path=/${application.subscriber-manager.alias}/actuator/**
          filters:
            - RewritePath=/${application.subscriber-manager.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of data actuator
        - id: data-actuator-actuator-base-path
          uri: http://localhost:${application.data-actuator.port}
          predicates:
            - Path=/${application.data-actuator.alias}/actuator
          filters:
            - RewritePath=/${application.data-actuator.alias}/actuator, /actuator
        - id: data-actuator-actuator-sub-paths
          uri: http://localhost:${application.data-actuator.port}
          predicates:
            - Path=/${application.data-actuator.alias}/actuator/**
          filters:
            - RewritePath=/${application.data-actuator.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of notificator email
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.notificator-email.port}
          predicates:
            - Path=/${application.notificator-email.alias}/actuator
          filters:
            - RewritePath=/${application.notificator-email.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.notificator-email.port}
          predicates:
            - Path=/${application.notificator-email.alias}/actuator/**
          filters:
            - RewritePath=/${application.notificator-email.alias}/actuator/(?<path>.*), /actuator/$\{path}

        ## actuator of notificator sms
        - id: subscriber-manager-actuator-base-path
          uri: http://localhost:${application.notificator-sms.port}
          predicates:
            - Path=/${application.notificator-sms.alias}/actuator
          filters:
            - RewritePath=/${application.notificator-sms.alias}/actuator, /actuator
        - id: subscriber-manager-actuator-sub-paths
          uri: http://localhost:${application.notificator-sms.port}
          predicates:
            - Path=/${application.notificator-sms.alias}/actuator/**
          filters:
            - RewritePath=/${application.notificator-sms.alias}/actuator/(?<path>.*), /actuator/$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${application.discovery-server.port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh
  endpoint:
    health:
      show-details: always