spring:
  rabbitmq:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8210/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, busrefresh
  endpoint:
    health:
      show-details: always