spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sbsdb

  liquibase:
    url: jdbc:postgresql://postgres:5432/sbsdb

  rabbitmq:
    host: rabbitmq

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8888/auth/realms/SubSystem
          jwk-set-uri: http://keycloak:8888/auth/realms/SubSystem/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8210/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
